### ISSUE TITLE
Android example not working: Could not communicate with server error#105

### ISSUE THREAD

**Issue by robertoost** [lufinkey/react-native-spotify#4]
I tried to run your example project on android, configured a spotify app on the developer platform (clientID, callback urls, package name and sha1 fingerprint) and got as far as the spotify login screen/dialogue in the example. After pressing the okay button (with correct login credentials) the dialogue closes.

```
		Spotify.login((loggedIn, error) => {
			if(error)
			{
                                // The code ends up here with this error log.
				console.log('Error logging in: ', error);
				Alert.alert("Error", error.message);
			}
                        ...
		});
```

which results in this error log:

```
{code: 105, message: "Could not communicate with server", domain: "RCTSpotifyErrorDomain"}
```

What is failing here? How can I run the example project in android successfully?

**Comment by lufinkey** [comment]
I'll check out this error and get back to you. Have you had the same issue on iOS or have you only tried Android so far?

**Comment by lufinkey** [comment]
May I also see the options you're passing into the initialize method? You can leave out the clientID since that's supposed to be secret

**Comment by adebree** [comment]
Thanks for your work @lufinkey ! I have the same issue as @robertoost, what I also noticed is that you probably forgot / missed committing ```android/gradlew``` and ```android/gradlew.bat``` into the example project (it's in the .gitignore of your library / root, but it should be present in the example project). I had to run an ```react-native upgrade``` and rolling back all the changes you did to the example project to get a working ```react-native run-android```.

But besides that, might it be that it's failing on the tokenSwapURL or tokenRefreshURL? We were not realizing we needed those. Can we use the URLs https://accounts.spotify.com/api/token for both? As we found here: https://developer.spotify.com/web-api/authorization-guide/#authorization-code-flow or do we need to run our own server side token implementation to get this working?

**Comment by lufinkey** [comment]
Should gradlew and gradlew.bat actually be committed? They're auto-generated files and I've had a lot of issues when they were committed vs when I started without them.

Also tokenSwapURL and tokenRefreshURL are not required, but they cannot be the spotify URL. You have to host it on your own (I know it's really dumb). You can use my [spotify-token-refresh-php](https://github.com/lufinkey/spotify-token-refresh-php) project and just make an appinfo.php following the example in appinfo.php.example.

Either way, it might be worth trying with a fresh download of the example project, because I just fixed a bunch of things

**Comment by lufinkey** [comment]
Please keep your issues with this project within this issue, and post your options for the Spotify.initialize method please

**Comment by robertoost** [comment]
It wasn't apparent at first that this was still a problem with this project, as the error changed after implementing the php project you linked to.

I retried on a local server after checking whether my values were correct, and it worked this time. It seems I didn't have to expose my server to the internet after all. @lufinkey, your assessments were spot-on. If anyone else receives this error, a local server was enough for me, and passing the values as such:
```
"tokenSwapURL":"{IP:PORT}/swap.php",
"tokenRefreshURL":"{IP:PORT}/refresh.php"
```
Seems sufficient to get past the login screen and into the player screen.

Thank you for the feedback, it helped a lot.
